'use client';

import { useState } from 'react';
import { Calculator, Info } from 'lucide-react';
import { StatusBadge } from '../../../../../components/atoms';
import { AnalysisNav } from '../../../../../components/molecules';
import InvestorPageShell from '../../../../../components/organisms/InvestorPageShell';
export default function FinancingPage() { const [rate, setRate] = useState(7.25); const monthly = Math.round(325000 * (rate / 1200) / (1 - Math.pow(1 + rate / 1200, -360))); return <InvestorPageShell eyebrow="Analysis · Financing" title="Financing model" description="Test debt assumptions and understand the cash required to acquire this property."><AnalysisNav active="Financing" /><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><section className="rounded-lg border border-[#DDE2DD] bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><Calculator size={18} className="text-[#173D2B]" /><h2 className="font-display text-2xl">Loan assumptions</h2></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Purchase price" value="325000" /><Field label="Down payment" value="20" suffix="%" /><label><span className="mb-2 flex justify-between text-xs font-semibold">Interest rate <span>{rate}%</span></span><input type="range" min="4" max="12" step="0.25" value={rate} onChange={(event) => setRate(Number(event.target.value))} className="w-full accent-[#173D2B]" /></label><Field label="Loan term" value="30" suffix="years" /></div></section><aside className="rounded-lg bg-[#173D2B] p-5 text-white"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#B7D83D]">Monthly debt service</p><p className="mt-2 font-display text-4xl">${monthly.toLocaleString()}</p><p className="mt-2 text-sm text-white/65">Principal and interest at {rate}%</p><div className="mt-6 space-y-3 border-t border-white/15 pt-4 text-sm"><div className="flex justify-between"><span className="text-white/60">Loan amount</span><span>$260,000</span></div><div className="flex justify-between"><span className="text-white/60">Cash to close</span><span>$81,500</span></div><div className="flex justify-between"><span className="text-white/60">DSCR</span><StatusBadge tone="positive">1.42</StatusBadge></div></div></aside></div><div className="mt-5 flex items-center gap-2 rounded-lg bg-[#E7F0F4] p-4 text-sm"><Info size={16} className="text-[#315A6B]" /> Financing outputs are estimates and should be confirmed with your lender.</div></InvestorPageShell>; }
function Field({ label, value, suffix }: { label: string; value: string; suffix?: string }) { return <label><span className="mb-2 block text-xs font-semibold">{label}</span><div className="relative"><input type="number" defaultValue={value} className="input w-full pr-16" />{suffix && <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-[#9AA8A0]">{suffix}</span>}</div></label>; }
