'use client';

import { useMemo, useState } from 'react';
import { Filter, Map, Search, SlidersHorizontal } from 'lucide-react';
import { PrimaryButton, StatusBadge } from '../../components/atoms';
import { OpportunityCard } from '../../components/molecules';
import InvestorPageShell from '../../components/organisms/InvestorPageShell';
import { investorProperties } from '../../lib/investor-data';

export default function PropertiesPage() {
  const [query, setQuery] = useState('');
  const [strategy, setStrategy] = useState('All strategies');
  const [mapOpen, setMapOpen] = useState(false);
  const filtered = useMemo(() => investorProperties.filter((property) => `${property.address} ${property.location}`.toLowerCase().includes(query.toLowerCase())), [query]);

  return <InvestorPageShell eyebrow="Opportunity finder" title="Discover properties" description="Search the intelligence layer across your target markets and find opportunities that fit your criteria." action={<PrimaryButton className="w-fit px-4 py-2.5 text-sm"><Search size={16} /> Save search</PrimaryButton>}>
    <div className="grid gap-5 xl:grid-cols-[230px_1fr_270px]">
      <aside className="h-fit rounded-lg border border-[#DDE2DD] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Filters</h2><button type="button" className="text-xs text-[#66706A]">Clear</button></div><div className="mt-5 space-y-5"><label className="block"><span className="mb-2 block text-xs font-semibold">Location</span><input className="input w-full text-sm" placeholder="City, ZIP or neighborhood" /></label><label className="block"><span className="mb-2 block text-xs font-semibold">Price range</span><div className="grid grid-cols-2 gap-2"><input className="input w-full text-sm" placeholder="$200k" /><input className="input w-full text-sm" placeholder="$500k" /></div></label><label className="block"><span className="mb-2 block text-xs font-semibold">Strategy</span><select className="input w-full text-sm" value={strategy} onChange={(event) => setStrategy(event.target.value)}><option>All strategies</option><option>Fix & Flip</option><option>Buy & Hold</option><option>BRRRR</option></select></label><label className="block"><span className="mb-2 block text-xs font-semibold">Minimum ROI</span><input type="range" min="0" max="30" defaultValue="15" className="w-full accent-[#173D2B]" /><div className="mt-1 flex justify-between text-[11px] text-[#9AA8A0]"><span>0%</span><span>15%+</span><span>30%</span></div></label><div className="flex flex-wrap gap-2"><StatusBadge tone="positive">Score 80+</StatusBadge><StatusBadge tone="neutral">Single family</StatusBadge></div></div></aside>
      <section><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9AA8A0]" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="input w-full pl-10" placeholder="Search address, city, ZIP..." /></div><button type="button" onClick={() => setMapOpen(!mapOpen)} className="btn-secondary flex items-center justify-center gap-2 px-4 py-2.5 text-sm"><Map size={16} /> {mapOpen ? 'Hide map' : 'Map view'}</button><button type="button" className="btn-secondary flex items-center justify-center gap-2 px-4 py-2.5 text-sm"><SlidersHorizontal size={16} /> Sort</button></div><div className="mt-5 flex items-center justify-between"><p className="text-sm text-[#66706A]"><span className="font-semibold text-[#172019]">{filtered.length * 12 + 4}</span> opportunities found</p><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#9AA8A0]">Updated 8 min ago</p></div>{mapOpen && <div className="mt-5 flex h-44 items-center justify-center overflow-hidden rounded-lg border border-[#DDE2DD] bg-[#E7F0E5] relative"><div className="absolute inset-0 opacity-40" style={{ backgroundImage: 'linear-gradient(#AFC6B1 1px, transparent 1px), linear-gradient(90deg, #AFC6B1 1px, transparent 1px)', backgroundSize: '32px 32px' }} /><div className="z-10 rounded-full bg-[#173D2B] px-3 py-2 text-xs font-semibold text-white">12 mapped opportunities</div></div>}<div className="mt-5 grid gap-4 md:grid-cols-2">{filtered.map((property) => <OpportunityCard key={property.address} property={property} />)}</div></section>
      <aside className="hidden h-fit rounded-lg border border-[#DDE2DD] bg-[#173D2B] p-5 text-white xl:block"><Filter className="text-[#B7D83D]" size={19} /><h2 className="mt-5 font-display text-2xl">Your search profile</h2><p className="mt-2 text-sm leading-6 text-white/65">These results reflect the criteria in your investor profile.</p><div className="mt-6 space-y-4 border-t border-white/15 pt-5 text-sm"><div className="flex justify-between"><span className="text-white/60">Target markets</span><span>TX metro</span></div><div className="flex justify-between"><span className="text-white/60">Capital range</span><span>$200k–$500k</span></div><div className="flex justify-between"><span className="text-white/60">Min. return</span><span>15% ROI</span></div></div><button type="button" className="mt-7 text-sm font-semibold text-[#B7D83D]">Edit criteria →</button></aside>
    </div>
  </InvestorPageShell>;
}
