/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/properties": {
    /**
     * Search properties
     * @description Search for properties based on various filters
     */
    get: operations["searchProperties"];
  };
  "/properties/{id}": {
    /**
     * Get property by ID
     * @description Retrieve detailed information about a specific property
     */
    get: operations["getProperty"];
  };
  "/properties/{id}/analyses": {
    /**
     * Create property analysis
     * @description Start a new property analysis job
     */
    post: operations["createPropertyAnalysis"];
  };
  "/analyses/{id}": {
    /**
     * Get analysis by ID
     * @description Retrieve the status and results of a property analysis
     */
    get: operations["getAnalysis"];
  };
  "/investor-profiles": {
    /**
     * Get investor profiles
     * @description Retrieve investor profiles (filtered by user's organization)
     */
    get: operations["getInvestorProfiles"];
    /**
     * Create investor profile
     * @description Create a new investor profile
     */
    post: operations["createInvestorProfile"];
  };
  "/investor-profiles/{id}": {
    /**
     * Get investor profile by ID
     * @description Retrieve a specific investor profile
     */
    get: operations["getInvestorProfile"];
    /**
     * Update investor profile
     * @description Update an existing investor profile
     */
    put: operations["updateInvestorProfile"];
  };
  "/investor-profiles/{id}/matches": {
    /**
     * Get property matches for investor
     * @description Retrieve properties that match the investor's criteria
     */
    get: operations["getInvestorMatches"];
  };
  "/offers": {
    /**
     * Get offers
     * @description Retrieve offers with optional filters
     */
    get: operations["getOffers"];
    /**
     * Create offer
     * @description Create a new offer for a property
     */
    post: operations["createOffer"];
  };
  "/offers/{id}": {
    /**
     * Get offer by ID
     * @description Retrieve a specific offer
     */
    get: operations["getOffer"];
  };
  "/deals": {
    /**
     * Get deals
     * @description Retrieve deals with optional filters
     */
    get: operations["getDeals"];
  };
  "/deals/{id}": {
    /**
     * Get deal by ID
     * @description Retrieve a specific deal with all details
     */
    get: operations["getDeal"];
  };
  "/documents/upload-url": {
    /**
     * Get document upload URL
     * @description Generate a pre-signed S3 URL for document upload
     */
    post: operations["getUploadUrl"];
  };
  "/jobs/{id}": {
    /**
     * Get job status
     * @description Check the status of a background job
     */
    get: operations["getJobStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Property: {
      /** Format: uuid */
      id?: string;
      canonicalAddress?: string;
      city?: string;
      stateCode?: string;
      postalCode?: string;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      longitude?: number;
      /** @enum {string} */
      propertyType?: "single_family" | "multi_family" | "condo" | "townhouse" | "land" | "commercial";
      bedrooms?: number;
      bathrooms?: number;
      buildingSqft?: number;
      lotSqft?: number;
      yearBuilt?: number;
      /** Format: double */
      estimatedValue?: number;
      /** Format: double */
      investmentScore?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    PropertyResponse: {
      data?: components["schemas"]["Property"];
      requestId?: string;
    };
    PropertySearchResponse: {
      data?: components["schemas"]["Property"][];
      pagination?: {
        page?: number;
        pageSize?: number;
        total?: number;
        hasMore?: boolean;
      };
      requestId?: string;
    };
    CreateAnalysisRequest: {
      /** @description Custom assumptions for the analysis */
      assumptions?: Record<string, never>;
    };
    AnalysisResponse: {
      data?: {
        id?: string;
        /** Format: uuid */
        propertyId?: string;
        /** @enum {string} */
        status?: "pending" | "processing" | "completed" | "failed";
        /** Format: double */
        estimatedValue?: number;
        /** Format: double */
        confidence?: number;
        modelName?: string;
        modelVersion?: string;
        comparableCount?: number;
        jobId?: string;
        /** Format: date-time */
        createdAt?: string;
      };
      requestId?: string;
    };
    InvestorProfile: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      userId?: string;
      displayName?: string;
      /** Format: double */
      capitalMin?: number;
      /** Format: double */
      capitalMax?: number;
      /** @enum {string} */
      strategy?: "fix_and_flip" | "buy_and_hold" | "rental" | "wholesale" | "development";
      /** Format: double */
      targetReturn?: number;
      /** @enum {string} */
      riskTolerance?: "low" | "medium" | "high";
      /** @enum {string} */
      renovationAppetite?: "none" | "light" | "moderate" | "heavy";
      propertyTypes?: string[];
      preferredStates?: string[];
      preferredCities?: string[];
      notificationEmail?: boolean;
      notificationSms?: boolean;
      notificationPush?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateInvestorProfileRequest: {
      displayName: string;
      /** Format: double */
      capitalMin?: number;
      /** Format: double */
      capitalMax?: number;
      /** @enum {string} */
      strategy: "fix_and_flip" | "buy_and_hold" | "rental" | "wholesale" | "development";
      /** Format: double */
      targetReturn?: number;
      /** @enum {string} */
      riskTolerance?: "low" | "medium" | "high";
      /** @enum {string} */
      renovationAppetite?: "none" | "light" | "moderate" | "heavy";
      propertyTypes?: string[];
      preferredStates?: string[];
      preferredCities?: string[];
    };
    UpdateInvestorProfileRequest: {
      displayName?: string;
      /** Format: double */
      capitalMin?: number;
      /** Format: double */
      capitalMax?: number;
      /** @enum {string} */
      strategy?: "fix_and_flip" | "buy_and_hold" | "rental" | "wholesale" | "development";
      /** Format: double */
      targetReturn?: number;
      /** @enum {string} */
      riskTolerance?: "low" | "medium" | "high";
      /** @enum {string} */
      renovationAppetite?: "none" | "light" | "moderate" | "heavy";
      propertyTypes?: string[];
      preferredStates?: string[];
      preferredCities?: string[];
    };
    InvestorProfileResponse: {
      data?: components["schemas"]["InvestorProfile"];
      requestId?: string;
    };
    InvestorProfilesResponse: {
      data?: components["schemas"]["InvestorProfile"][];
      requestId?: string;
    };
    PropertyMatch: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      investorId?: string;
      /** Format: uuid */
      propertyId?: string;
      /** Format: double */
      score?: number;
      reasons?: string[];
      isViewed?: boolean;
      isSaved?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    PropertyMatchesResponse: {
      data?: components["schemas"]["PropertyMatch"][];
      pagination?: {
        page?: number;
        pageSize?: number;
        total?: number;
        hasMore?: boolean;
      };
      requestId?: string;
    };
    Offer: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      propertyId?: string;
      /** Format: uuid */
      investorId?: string;
      /** @enum {string} */
      status?: "draft" | "submitted" | "under_review" | "accepted" | "rejected" | "countered" | "expired";
      /** Format: double */
      offeredPrice?: number;
      terms?: Record<string, never>;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateOfferRequest: {
      /** Format: uuid */
      propertyId: string;
      /** Format: double */
      offeredPrice: number;
      terms?: Record<string, never>;
      /** Format: date-time */
      expiresAt?: string;
    };
    OfferResponse: {
      data?: components["schemas"]["Offer"];
      requestId?: string;
    };
    OffersResponse: {
      data?: components["schemas"]["Offer"][];
      pagination?: {
        page?: number;
        pageSize?: number;
        total?: number;
        hasMore?: boolean;
      };
      requestId?: string;
    };
    Deal: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      propertyId?: string;
      /** Format: uuid */
      offerId?: string;
      /** @enum {string} */
      status?: "initiated" | "due_diligence" | "contracted" | "financing" | "closing" | "closed" | "cancelled";
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      milestones?: ({
          /** Format: uuid */
          id?: string;
          name?: string;
          /** @enum {string} */
          status?: "pending" | "in_progress" | "completed" | "blocked";
          /** Format: date-time */
          dueDate?: string;
          /** Format: date-time */
          completedAt?: string;
        })[];
      participants?: ({
          /** Format: uuid */
          userId?: string;
          /** @enum {string} */
          role?: "buyer" | "seller" | "agent" | "coordinator" | "lender" | "attorney";
        })[];
    };
    DealResponse: {
      data?: components["schemas"]["Deal"];
      requestId?: string;
    };
    DealsResponse: {
      data?: components["schemas"]["Deal"][];
      pagination?: {
        page?: number;
        pageSize?: number;
        total?: number;
        hasMore?: boolean;
      };
      requestId?: string;
    };
    UploadUrlRequest: {
      documentType: string;
      /** Format: uuid */
      propertyId?: string;
      /** Format: uuid */
      dealId?: string;
      fileName: string;
      contentType: string;
      fileSize?: number;
    };
    UploadUrlResponse: {
      data?: {
        uploadUrl?: string;
        s3Key?: string;
        /** Format: date-time */
        expiresAt?: string;
      };
      requestId?: string;
    };
    Job: {
      id?: string;
      jobType?: string;
      /** @enum {string} */
      status?: "pending" | "processing" | "completed" | "failed";
      progress?: number;
      errorMessage?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      startedAt?: string;
      /** Format: date-time */
      completedAt?: string;
    };
    JobResponse: {
      data?: components["schemas"]["Job"];
      requestId?: string;
    };
    ErrorResponse: {
      error?: {
        code?: string;
        message?: string;
        requestId?: string;
        details?: Record<string, never>;
      };
      requestId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Search properties
   * @description Search for properties based on various filters
   */
  searchProperties: {
    parameters: {
      query?: {
        /** @description Search by address */
        address?: string;
        /** @description Filter by city */
        city?: string;
        /** @description Filter by state code */
        stateCode?: string;
        /** @description Filter by postal code */
        postalCode?: string;
        /** @description Filter by property type */
        propertyType?: ("single_family" | "multi_family" | "condo" | "townhouse" | "land" | "commercial")[];
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        pageSize?: number;
      };
    };
    responses: {
      /** @description Properties found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["PropertySearchResponse"];
        };
      };
      /** @description Invalid request parameters */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get property by ID
   * @description Retrieve detailed information about a specific property
   */
  getProperty: {
    parameters: {
      path: {
        /** @description Property ID */
        id: string;
      };
    };
    responses: {
      /** @description Property found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyResponse"];
        };
      };
      /** @description Property not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Create property analysis
   * @description Start a new property analysis job
   */
  createPropertyAnalysis: {
    parameters: {
      path: {
        /** @description Property ID */
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateAnalysisRequest"];
      };
    };
    responses: {
      /** @description Analysis job created successfully */
      202: {
        content: {
          "application/json": components["schemas"]["AnalysisResponse"];
        };
      };
      /** @description Property not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get analysis by ID
   * @description Retrieve the status and results of a property analysis
   */
  getAnalysis: {
    parameters: {
      path: {
        /** @description Analysis ID */
        id: string;
      };
    };
    responses: {
      /** @description Analysis found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["AnalysisResponse"];
        };
      };
      /** @description Analysis not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get investor profiles
   * @description Retrieve investor profiles (filtered by user's organization)
   */
  getInvestorProfiles: {
    responses: {
      /** @description Investor profiles retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["InvestorProfilesResponse"];
        };
      };
    };
  };
  /**
   * Create investor profile
   * @description Create a new investor profile
   */
  createInvestorProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvestorProfileRequest"];
      };
    };
    responses: {
      /** @description Investor profile created successfully */
      201: {
        content: {
          "application/json": components["schemas"]["InvestorProfileResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get investor profile by ID
   * @description Retrieve a specific investor profile
   */
  getInvestorProfile: {
    parameters: {
      path: {
        /** @description Investor profile ID */
        id: string;
      };
    };
    responses: {
      /** @description Investor profile found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["InvestorProfileResponse"];
        };
      };
      /** @description Investor profile not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Update investor profile
   * @description Update an existing investor profile
   */
  updateInvestorProfile: {
    parameters: {
      path: {
        /** @description Investor profile ID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateInvestorProfileRequest"];
      };
    };
    responses: {
      /** @description Investor profile updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["InvestorProfileResponse"];
        };
      };
      /** @description Investor profile not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get property matches for investor
   * @description Retrieve properties that match the investor's criteria
   */
  getInvestorMatches: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        pageSize?: number;
      };
      path: {
        /** @description Investor profile ID */
        id: string;
      };
    };
    responses: {
      /** @description Property matches retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyMatchesResponse"];
        };
      };
    };
  };
  /**
   * Get offers
   * @description Retrieve offers with optional filters
   */
  getOffers: {
    parameters: {
      query?: {
        /** @description Filter by property ID */
        propertyId?: string;
        /** @description Filter by investor ID */
        investorId?: string;
        /** @description Filter by status */
        status?: "draft" | "submitted" | "under_review" | "accepted" | "rejected" | "countered" | "expired";
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        pageSize?: number;
      };
    };
    responses: {
      /** @description Offers retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["OffersResponse"];
        };
      };
    };
  };
  /**
   * Create offer
   * @description Create a new offer for a property
   */
  createOffer: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOfferRequest"];
      };
    };
    responses: {
      /** @description Offer created successfully */
      201: {
        content: {
          "application/json": components["schemas"]["OfferResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get offer by ID
   * @description Retrieve a specific offer
   */
  getOffer: {
    parameters: {
      path: {
        /** @description Offer ID */
        id: string;
      };
    };
    responses: {
      /** @description Offer found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["OfferResponse"];
        };
      };
      /** @description Offer not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get deals
   * @description Retrieve deals with optional filters
   */
  getDeals: {
    parameters: {
      query?: {
        /** @description Filter by property ID */
        propertyId?: string;
        /** @description Filter by status */
        status?: "initiated" | "due_diligence" | "contracted" | "financing" | "closing" | "closed" | "cancelled";
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        pageSize?: number;
      };
    };
    responses: {
      /** @description Deals retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["DealsResponse"];
        };
      };
    };
  };
  /**
   * Get deal by ID
   * @description Retrieve a specific deal with all details
   */
  getDeal: {
    parameters: {
      path: {
        /** @description Deal ID */
        id: string;
      };
    };
    responses: {
      /** @description Deal found successfully */
      200: {
        content: {
          "application/json": components["schemas"]["DealResponse"];
        };
      };
      /** @description Deal not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get document upload URL
   * @description Generate a pre-signed S3 URL for document upload
   */
  getUploadUrl: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadUrlRequest"];
      };
    };
    responses: {
      /** @description Upload URL generated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UploadUrlResponse"];
        };
      };
    };
  };
  /**
   * Get job status
   * @description Check the status of a background job
   */
  getJobStatus: {
    parameters: {
      path: {
        /** @description Job ID */
        id: string;
      };
    };
    responses: {
      /** @description Job status retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["JobResponse"];
        };
      };
      /** @description Job not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
