'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, CircleDollarSign, FileCheck2, Info } from 'lucide-react';
import { PrimaryButton, StatusBadge } from '../../../../../components/atoms';
import SellerPageShell from '../../../../../components/organisms/SellerPageShell';

type Stage = 'edit' | 'review' | 'sent';

export default function CounterOfferPage() {
  const [stage, setStage] = useState<Stage>('edit');
  const [price, setPrice] = useState('325000');
  const [earnestMoney, setEarnestMoney] = useState('12000');
  const [closingDate, setClosingDate] = useState('October 10, 2026');
  const [inspection, setInspection] = useState('10 days');
  const [expiration, setExpiration] = useState('September 6, 2026');

  return <SellerPageShell eyebrow="Offer negotiation" title={stage === 'sent' ? 'Counter offer sent' : 'Create counter offer'} description="Offer #12345 · 123 Main Street · Investor #A103">
    {stage !== 'sent' && <div className="mb-6 flex items-center gap-2 text-sm"><Link href="/seller/offers/12345" className="font-semibold text-[#173D2B]">Offer detail</Link><ArrowRight size={14} className="text-[#9AA8A0]" /><span className="text-[#66706A]">{stage === 'edit' ? 'Counter terms' : 'Review and send'}</span></div>}
    {stage === 'edit' && <EditStage price={price} setPrice={setPrice} earnestMoney={earnestMoney} setEarnestMoney={setEarnestMoney} closingDate={closingDate} setClosingDate={setClosingDate} inspection={inspection} setInspection={setInspection} expiration={expiration} setExpiration={setExpiration} onContinue={() => setStage('review')} />}
    {stage === 'review' && <ReviewStage price={price} earnestMoney={earnestMoney} closingDate={closingDate} inspection={inspection} expiration={expiration} onBack={() => setStage('edit')} onSend={() => setStage('sent')} />}
    {stage === 'sent' && <SentStage />}
  </SellerPageShell>;
}

function EditStage({ price, setPrice, earnestMoney, setEarnestMoney, closingDate, setClosingDate, inspection, setInspection, expiration, setExpiration, onContinue }: { price: string; setPrice: (value: string) => void; earnestMoney: string; setEarnestMoney: (value: string) => void; closingDate: string; setClosingDate: (value: string) => void; inspection: string; setInspection: (value: string) => void; expiration: string; setExpiration: (value: string) => void; onContinue: () => void }) {
  return <div className="grid max-w-5xl gap-5 xl:grid-cols-[1fr_320px]"><section className="rounded-lg border border-[#DDE2DD] bg-white p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9AA8A0]">Step 1 of 2</p><h2 className="mt-2 font-display text-3xl">Set your counter terms</h2><p className="mt-2 text-sm text-[#66706A]">Adjust the original offer and add terms for the investor to review.</p></div><StatusBadge tone="warning">Original: $315,000</StatusBadge></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Counter price" value={price} onChange={setPrice} prefix="$" /><Field label="Earnest money" value={earnestMoney} onChange={setEarnestMoney} prefix="$" /><Field label="Closing date" value={closingDate} onChange={setClosingDate} /><Field label="Inspection period" value={inspection} onChange={setInspection} /><Field label="Counter expiration" value={expiration} onChange={setExpiration} /></div><label className="mt-5 block"><span className="mb-2 block text-xs font-semibold">Additional terms</span><textarea className="input min-h-28 w-full" defaultValue="Seller to provide available property disclosures. Buyer to confirm financing within 5 business days." /></label><div className="mt-6 flex items-start gap-2 rounded-md bg-[#E7F0F4] p-3 text-xs leading-5 text-[#66706A]"><Info size={14} className="mt-0.5 shrink-0 text-[#315A6B]" /> Sending this counter offer will move the offer back to the investor for review.</div><div className="mt-7 flex justify-between"><Link href="/seller/offers/12345" className="flex items-center gap-2 text-sm font-semibold text-[#66706A]"><ArrowLeft size={15} /> Cancel</Link><PrimaryButton onClick={onContinue} className="px-4 py-2.5 text-sm">Review counter <ArrowRight size={15} /></PrimaryButton></div></section><aside className="rounded-lg bg-[#173D2B] p-5 text-white"><CircleDollarSign className="text-[#B7D83D]" size={19} /><p className="mt-5 font-mono text-[10px] uppercase tracking-[0.14em] text-[#B7D83D]">Negotiation context</p><h2 className="mt-2 font-display text-3xl">$315,000</h2><p className="mt-1 text-sm text-white/65">Investor’s original offer</p><div className="mt-6 space-y-3 border-t border-white/15 pt-4 text-sm"><p className="flex justify-between"><span className="text-white/60">Financing</span><span>Conventional</span></p><p className="flex justify-between"><span className="text-white/60">Original closing</span><span>Oct 10</span></p><p className="flex justify-between"><span className="text-white/60">Investor</span><span>#A103</span></p></div></aside></div>;
}

function ReviewStage({ price, earnestMoney, closingDate, inspection, expiration, onBack, onSend }: { price: string; earnestMoney: string; closingDate: string; inspection: string; expiration: string; onBack: () => void; onSend: () => void }) {
  return <div className="grid max-w-5xl gap-5 xl:grid-cols-[1fr_320px]"><section className="rounded-lg border border-[#DDE2DD] bg-white p-5 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9AA8A0]">Step 2 of 2</p><h2 className="mt-2 font-display text-3xl">Review your counter</h2><p className="mt-2 text-sm text-[#66706A]">Confirm the terms before sending them to the investor.</p><div className="mt-7 divide-y divide-[#E8EBE8] rounded-md border border-[#DDE2DD]">{[['Property', '123 Main Street · Dallas, TX'], ['Counter price', `$${Number(price).toLocaleString()}`], ['Earnest money', `$${Number(earnestMoney).toLocaleString()}`], ['Closing date', closingDate], ['Inspection period', inspection], ['Expiration', expiration], ['Financing', 'Conventional']].map(([label, value]) => <div key={label} className="flex justify-between gap-4 p-4 text-sm"><span className="text-[#66706A]">{label}</span><span className="text-right font-semibold">{value}</span></div>)}</div><div className="mt-6 flex items-start gap-3 rounded-md bg-[#FFF3D7] p-4 text-sm"><FileCheck2 size={17} className="mt-0.5 shrink-0 text-[#8A5C08]" /><p><span className="font-semibold">This action is recorded.</span><span className="mt-1 block text-xs leading-5 text-[#745521]">The investor will receive the counter and the offer status will become Countered.</span></p></div><div className="mt-7 flex justify-between"><button type="button" onClick={onBack} className="flex items-center gap-2 text-sm font-semibold text-[#66706A]"><ArrowLeft size={15} /> Edit terms</button><PrimaryButton onClick={onSend} className="px-4 py-2.5 text-sm">Send counter offer <ArrowRight size={15} /></PrimaryButton></div></section><aside className="rounded-lg border border-[#DDE2DD] bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9AA8A0]">What happens next</p><div className="mt-5 space-y-4 text-sm"><p className="flex gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#E8F5D3] text-xs font-semibold">1</span> Investor is notified</p><p className="flex gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#E8F5D3] text-xs font-semibold">2</span> They accept, counter, or decline</p><p className="flex gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#E8F5D3] text-xs font-semibold">3</span> The timeline records the response</p></div></aside></div>;
}

function SentStage() { return <section className="max-w-2xl rounded-lg border border-[#DDE2DD] bg-white p-8 text-center sm:p-12"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#B7D83D] text-[#173D2B]"><Check size={25} /></span><h2 className="mt-6 font-display text-3xl">Counter offer sent</h2><p className="mt-3 text-sm leading-6 text-[#66706A]">Your counter offer for 123 Main Street was sent to Investor #A103. The offer is now waiting for their response.</p><div className="mx-auto mt-7 max-w-sm rounded-md bg-[#F7F8F6] p-4 text-left text-sm"><p className="font-semibold">Offer #12345</p><p className="mt-2 text-[#66706A]">Status <b className="text-[#8A5C08]">Countered</b></p><p className="mt-1 text-[#66706A]">Timeline updated just now</p></div><Link href="/seller/offers/12345" className="btn-primary mt-7 inline-flex px-4 py-2.5 text-sm">View offer timeline</Link></section>; }
function Field({ label, value, onChange, prefix }: { label: string; value: string; onChange: (value: string) => void; prefix?: string }) { return <label className="block"><span className="mb-2 block text-xs font-semibold">{label}</span><div className="relative">{prefix && <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9AA8A0]">{prefix}</span>}<input className={`input w-full ${prefix ? 'pl-7' : ''}`} value={value} onChange={(event) => onChange(event.target.value)} /></div></label>; }
