'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, ChevronRight, FileText } from 'lucide-react';
import { PrimaryButton, StatusBadge } from '../../../../components/atoms';
import InvestorPageShell from '../../../../components/organisms/InvestorPageShell';
export default function NewOfferPage() { const [submitted, setSubmitted] = useState(false); return <InvestorPageShell eyebrow="Transaction center" title="Create an offer" description="4812 Elm Street · Oak Lawn, Dallas TX"><Link href="/investor/offers" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#173D2B]"><ArrowLeft size={15} /> Back to offers</Link>{submitted ? <section className="max-w-2xl rounded-lg border border-[#DDE2DD] bg-white p-8 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#E8F5D3] text-[#31551C]"><Check /></span><h2 className="mt-5 font-display text-3xl">Offer submitted</h2><p className="mt-2 text-sm text-[#66706A]">Your offer has been sent to the authorized seller team and is now under review.</p><Link href="/investor/offers/12346" className="btn-primary mt-6 inline-flex px-4 py-2.5 text-sm">View offer status</Link></section> : <div className="grid gap-5 xl:grid-cols-[1fr_330px]"><section className="rounded-lg border border-[#DDE2DD] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Offer terms</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Offer price" value="$315,000" /><Field label="Earnest money" value="$6,500" /><Field label="Financing type" value="Conventional" select /><Field label="Closing date" value="October 10, 2026" /><Field label="Inspection period" value="10 days" /><Field label="Offer expiration" value="September 6, 2026" /></div><label className="mt-5 block"><span className="mb-2 block text-xs font-semibold">Other terms</span><textarea className="input min-h-24 w-full" placeholder="Add contingencies or special terms..." /></label><label className="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" className="accent-[#173D2B]" /> I confirm these terms are accurate and authorize submission.</label><PrimaryButton onClick={() => setSubmitted(true)} className="mt-7 px-4 py-2.5 text-sm">Review and submit <ChevronRight size={16} /></PrimaryButton></section><aside className="h-fit rounded-lg border border-[#DDE2DD] bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9AA8A0]">Offer preview</p><h2 className="mt-2 font-display text-2xl">$315,000</h2><p className="mt-1 text-sm text-[#66706A]">4812 Elm Street</p><div className="mt-5 space-y-3 border-t border-[#E8EBE8] pt-5 text-sm"><p className="flex justify-between"><span className="text-[#66706A]">Financing</span><span>Conventional</span></p><p className="flex justify-between"><span className="text-[#66706A]">Closing</span><span>Oct 10</span></p><p className="flex justify-between"><span className="text-[#66706A]">Inspection</span><span>10 days</span></p></div><p className="mt-6 flex items-center gap-2 text-xs text-[#66706A]"><FileText size={14} /> Attachments can be added after review.</p></aside></div>}</InvestorPageShell>; }
function Field({ label, value, select }: { label: string; value: string; select?: boolean }) { return <label className="block"><span className="mb-2 block text-xs font-semibold">{label}</span>{select ? <select className="input w-full" defaultValue={value}><option>{value}</option><option>Cash</option><option>Hard money</option></select> : <input className="input w-full" defaultValue={value} />}</label>; }
