'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, FileText, ImagePlus, Info, MapPin, ShieldCheck, Upload } from 'lucide-react';
import { PrimaryButton, StatusBadge } from '../../../../components/atoms';
import SellerPageShell from '../../../../components/organisms/SellerPageShell';

type Step = 'address' | 'access' | 'details' | 'condition' | 'media' | 'review' | 'complete';
const steps: { id: Step; label: string }[] = [
  { id: 'address', label: 'Address' },
  { id: 'access', label: 'Access' },
  { id: 'details', label: 'Details' },
  { id: 'condition', label: 'Condition' },
  { id: 'media', label: 'Media' },
  { id: 'review', label: 'Review' },
];

export default function AddPropertyPage() {
  const [step, setStep] = useState<Step>('address');
  const [found, setFound] = useState(false);
  const [accessMode, setAccessMode] = useState<'claim' | 'create'>('claim');
  const [photoCount, setPhotoCount] = useState(5);
  const [documentCount, setDocumentCount] = useState(2);

  const currentIndex = steps.findIndex((item) => item.id === step);
  const next = () => setStep(currentIndex >= steps.length - 1 ? 'complete' : steps[currentIndex + 1].id);
  const back = () => setStep(currentIndex <= 0 ? 'address' : steps[currentIndex - 1].id);

  return <SellerPageShell eyebrow="Property management" title={step === 'complete' ? 'Property added' : 'Add a property'} description={step === 'complete' ? 'Your property workspace is ready for listing and intelligence review.' : 'Create a trusted property record, add your information, and prepare it for the marketplace.'}>
    {step !== 'complete' && <StepProgress current={currentIndex} />}
    {step === 'address' && <AddressStep found={found} onFind={() => { setFound(true); setStep('access'); }} />}
    {step === 'access' && <AccessStep found={found} mode={accessMode} onModeChange={setAccessMode} />}
    {step === 'details' && <DetailsStep />}
    {step === 'condition' && <ConditionStep />}
    {step === 'media' && <MediaStep photoCount={photoCount} documentCount={documentCount} onPhotos={() => setPhotoCount(photoCount + 1)} onDocuments={() => setDocumentCount(documentCount + 1)} />}
    {step === 'review' && <ReviewStep found={found} photoCount={photoCount} documentCount={documentCount} />}
    {step === 'complete' && <CompleteStep />}
    {step !== 'address' && step !== 'complete' && <div className="mt-6 flex max-w-3xl items-center justify-between"><button type="button" onClick={back} className="flex items-center gap-2 text-sm font-semibold text-[#66706A] hover:text-[#172019]"><ArrowLeft size={15} /> Back</button><PrimaryButton onClick={next} className="px-5 py-2.5 text-sm">{step === 'review' ? 'Create property workspace' : 'Continue'} <ArrowRight size={15} /></PrimaryButton></div>}
  </SellerPageShell>;
}

function StepProgress({ current }: { current: number }) { return <div className="mb-8 max-w-3xl overflow-x-auto"><div className="flex min-w-[620px] items-start">{steps.map((item, index) => <div key={item.id} className="relative flex flex-1 flex-col items-center"><div className={`z-10 flex h-8 w-8 items-center justify-center rounded-full text-xs font-semibold ${index < current ? 'bg-[#B7D83D] text-[#173D2B]' : index === current ? 'bg-[#173D2B] text-white' : 'border border-[#DDE2DD] bg-white text-[#9AA8A0]'}`}>{index < current ? <Check size={14} /> : index + 1}</div>{index < steps.length - 1 && <div className={`absolute left-1/2 top-4 h-px w-full ${index < current ? 'bg-[#B7D83D]' : 'bg-[#DDE2DD]'}`} />}<span className={`mt-2 text-[10px] ${index === current ? 'font-semibold text-[#173D2B]' : 'text-[#9AA8A0]'}`}>{item.label}</span></div>)}</div></div>; }

function AddressStep({ found, onFind }: { found: boolean; onFind: () => void }) { return <StepCard eyebrow="Step 1 of 6" title="Find your property" description="We'll match your address to an existing platform record before creating anything new."><div className="grid gap-4 sm:grid-cols-[1fr_120px]"><Field label="Street address" value="123 Main Street" /><Field label="ZIP code" value="75201" /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="City" value="Dallas" /><Field label="State" value="TX" /></div>{found && <div className="mt-6 rounded-md border border-[#B7D83D] bg-[#E8F5D3] p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Check size={16} className="text-[#31551C]" /> Existing property record found</p><p className="mt-2 text-sm">123 Main Street · Dallas, TX 75201</p><p className="mt-1 text-xs text-[#66706A]">Verified facts and existing property intelligence are available.</p></div>}<div className="mt-6 flex items-start gap-3 rounded-md bg-[#E7F0F4] p-4 text-xs leading-5 text-[#66706A]"><MapPin size={15} className="mt-0.5 shrink-0 text-[#315A6B]" /> We use the address to prevent duplicate property records and preserve authoritative data provenance.</div><PrimaryButton onClick={onFind} className="mt-7 px-4 py-2.5 text-sm">{found ? 'Use this property' : 'Find property'} <ArrowRight size={15} /></PrimaryButton></StepCard>; }

function AccessStep({ found, mode, onModeChange }: { found: boolean; mode: 'claim' | 'create'; onModeChange: (mode: 'claim' | 'create') => void }) { return <StepCard eyebrow="Step 2 of 6" title={found ? 'Confirm property access' : 'Choose a property path'} description={found ? 'This property already exists in Qurasion. Choose how you want to continue.' : 'You can claim an existing record or create a new one for review.'}><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => onModeChange('claim')} className={`rounded-md border p-5 text-left ${mode === 'claim' ? 'border-[#173D2B] bg-[#E8F5D3]' : 'border-[#DDE2DD]'}`}><ShieldCheck className="text-[#31551C]" size={19} /><p className="mt-4 font-semibold">Claim this property</p><p className="mt-1 text-xs leading-5 text-[#66706A]">Verify you are authorized to manage the existing record.</p></button><button type="button" onClick={() => onModeChange('create')} className={`rounded-md border p-5 text-left ${mode === 'create' ? 'border-[#173D2B] bg-[#E8F5D3]' : 'border-[#DDE2DD]'}`}><FileText className="text-[#173D2B]" size={19} /><p className="mt-4 font-semibold">Create new record</p><p className="mt-1 text-xs leading-5 text-[#66706A]">Start a new property record if the match is not yours.</p></button></div><div className="mt-6 rounded-md bg-[#F7F8F6] p-4 text-sm"><p className="font-semibold">{mode === 'claim' ? 'Ownership verification' : 'Record review'}</p><p className="mt-1 text-xs leading-5 text-[#66706A]">{mode === 'claim' ? 'You will be able to upload ownership or representation evidence after continuing.' : 'New records are reviewed before they can be published to the marketplace.'}</p></div></StepCard>; }

function DetailsStep() { return <StepCard eyebrow="Step 3 of 6" title="Property details" description="Review platform facts and add details that help buyers understand the property."><div className="grid gap-5 sm:grid-cols-2">{[['Property type', 'Single family'], ['Bedrooms', '3'], ['Bathrooms', '2'], ['Square feet', '1,850'], ['Lot size', '0.18 acres'], ['Year built', '1988'], ['Parking', '2-car garage'], ['Stories', '1']].map(([label, value]) => <div key={label}><Field label={label} value={value} /><p className="mt-1 text-[10px] text-[#9AA8A0]">Platform record · editable suggestion</p></div>)}</div><label className="mt-5 block"><span className="mb-2 block text-xs font-semibold">Seller notes</span><textarea className="input min-h-24 w-full" placeholder="Recent improvements, features, or context for reviewers..." /></label></StepCard>; }

function ConditionStep() { return <StepCard eyebrow="Step 4 of 6" title="Property condition" description="Tell us what needs attention. Unknown is a valid answer and can be updated later."><label className="block"><span className="mb-3 block text-xs font-semibold">Overall condition</span><div className="grid gap-2 sm:grid-cols-5">{['Excellent', 'Good', 'Fair', 'Poor', 'Needs renovation'].map((item, index) => <button type="button" key={item} className={`rounded-md border p-3 text-xs ${index === 1 ? 'border-[#173D2B] bg-[#E8F5D3] font-semibold' : 'border-[#DDE2DD] text-[#66706A]'}`}>{item}</button>)}</div></label><div className="mt-7 grid gap-4 sm:grid-cols-2">{['Roof', 'HVAC', 'Plumbing', 'Electrical', 'Kitchen', 'Bathrooms', 'Foundation', 'Exterior'].map((item) => <label key={item}><span className="mb-2 block text-xs font-semibold">{item}</span><select className="input w-full"><option>Good</option><option>Excellent</option><option>Fair</option><option>Poor</option><option>Unknown</option></select></label>)}</div><div className="mt-6 rounded-md bg-[#FFF3D7] p-4 text-xs leading-5 text-[#745521]"><Info className="mb-1 inline" size={14} /> Condition answers inform listing context and model confidence but do not overwrite authoritative property facts.</div></StepCard>; }

function MediaStep({ photoCount, documentCount, onPhotos, onDocuments }: { photoCount: number; documentCount: number; onPhotos: () => void; onDocuments: () => void }) { return <StepCard eyebrow="Step 5 of 6" title="Photos and documents" description="Add enough context for buyers and reviewers to understand the property." ><div className="grid gap-4 sm:grid-cols-2"><button type="button" onClick={onPhotos} className="rounded-lg border border-dashed border-[#B9C5BA] p-6 text-left hover:border-[#173D2B]"><ImagePlus className="text-[#173D2B]" size={20} /><p className="mt-4 font-semibold">Property photos</p><p className="mt-1 text-xs text-[#66706A]">{photoCount} photos added · exterior, interior, kitchen, bedrooms</p><span className="mt-4 flex items-center gap-1 text-xs font-semibold text-[#173D2B]"><Upload size={14} /> Add photo</span></button><button type="button" onClick={onDocuments} className="rounded-lg border border-dashed border-[#B9C5BA] p-6 text-left hover:border-[#173D2B]"><FileText className="text-[#173D2B]" size={20} /><p className="mt-4 font-semibold">Property documents</p><p className="mt-1 text-xs text-[#66706A]">{documentCount} documents added · tax records, permits, inspection</p><span className="mt-4 flex items-center gap-1 text-xs font-semibold text-[#173D2B]"><Upload size={14} /> Add document</span></button></div><div className="mt-6 rounded-md bg-[#F7F8F6] p-4 text-xs leading-5 text-[#66706A]">Photos can be reordered and one can be selected as the cover image after the workspace is created.</div></StepCard>; }

function ReviewStep({ found, photoCount, documentCount }: { found: boolean; photoCount: number; documentCount: number }) { return <StepCard eyebrow="Step 6 of 6" title="Review property workspace" description="Confirm the information before creating your seller property workspace."><div className="divide-y divide-[#E8EBE8] rounded-md border border-[#DDE2DD]"><ReviewRow label="Property" value="123 Main Street · Dallas, TX 75201" /><ReviewRow label="Access" value={found ? 'Claim existing platform record' : 'Create new property record'} /><ReviewRow label="Property details" value="3 beds · 2 baths · 1,850 sqft · Single family" /><ReviewRow label="Media" value={`${photoCount} photos · ${documentCount} documents`} /><ReviewRow label="Initial status" value="Pending verification" /></div><div className="mt-6 flex items-start gap-3 rounded-md bg-[#E8F5D3] p-4 text-sm"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[#31551C]" /><p><span className="font-semibold">Ready to create.</span><span className="mt-1 block text-xs leading-5 text-[#66706A]">You can edit permitted information and complete verification from the new property workspace.</span></p></div></StepCard>; }

function CompleteStep() { return <div className="max-w-2xl rounded-lg border border-[#DDE2DD] bg-white p-8 text-center sm:p-12"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#B7D83D] text-[#173D2B]"><Check size={24} /></span><h2 className="mt-6 font-display text-3xl">Property workspace created</h2><p className="mt-3 text-sm leading-6 text-[#66706A]">123 Main Street is pending verification. Add listing details, review intelligence, and prepare it for investors.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/seller/properties/main-street" className="btn-primary px-4 py-2.5 text-sm">Open property workspace</Link><Link href="/seller/properties" className="btn-secondary px-4 py-2.5 text-sm">View my properties</Link></div></div>; }

function StepCard({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="max-w-3xl rounded-lg border border-[#DDE2DD] bg-white p-5 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9AA8A0]">{eyebrow}</p><h2 className="mt-2 font-display text-3xl">{title}</h2><p className="mt-2 text-sm leading-6 text-[#66706A]">{description}</p><div className="mt-7">{children}</div></section>; }
function Field({ label, value }: { label: string; value: string }) { return <label className="block"><span className="mb-2 block text-xs font-semibold">{label}</span><input className="input w-full" defaultValue={value} /></label>; }
function ReviewRow({ label, value }: { label: string; value: string }) { return <div className="flex flex-col gap-1 p-4 sm:flex-row sm:items-center"><span className="w-36 text-xs text-[#66706A]">{label}</span><span className="text-sm font-semibold">{value}</span></div>; }
