export const buyerProperties = [
  {
    id: 'prop-1',
    slug: '1824-oak-street-austin-tx',
    address: '1824 Oak Street',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    price: 450000,
    type: 'House',
    bedrooms: 3,
    bathrooms: 2,
    size: 1850,
    lotSize: 5200,
    yearBuilt: 2015,
    status: 'For Sale',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
    ],
    description: 'Beautiful modern home in the heart of Austin. Features open floor plan, gourmet kitchen, and spacious backyard perfect for entertaining.',
    features: ['Garage', 'Pool', 'Garden', 'Central AC', 'Hardwood Floors'],
    estimatedValue: { min: 440000, max: 465000 },
    monthlyRent: null,
    nightlyRate: null,
    rating: null,
    reviews: null,
    availability: null,
  },
  {
    id: 'prop-2',
    slug: '741-pine-avenue-dallas-tx',
    address: '741 Pine Avenue',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    price: null,
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 1,
    size: 950,
    lotSize: null,
    yearBuilt: 2020,
    status: 'For Rent',
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
    ],
    description: 'Modern apartment in downtown Dallas with stunning city views. Walking distance to restaurants and entertainment.',
    features: ['Gym', 'Rooftop', 'Concierge', 'Parking', 'Pet Friendly'],
    estimatedValue: null,
    monthlyRent: 2400,
    nightlyRate: null,
    rating: null,
    reviews: null,
    availability: 'Oct 1, 2026',
  },
  {
    id: 'prop-3',
    slug: '92-market-street-lisbon-portugal',
    address: '92 Market Street',
    city: 'Lisbon',
    state: null,
    zip: '1100-000',
    price: null,
    type: 'Condo',
    bedrooms: 2,
    bathrooms: 1,
    size: 800,
    lotSize: null,
    yearBuilt: 2018,
    status: 'Short-term Stay',
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80',
    ],
    description: 'Charming apartment in historic Lisbon district. Perfect for exploring the city with easy access to public transportation.',
    features: ['Wi-Fi', 'Kitchen', 'Washer', 'Air Conditioning', 'City View'],
    estimatedValue: null,
    monthlyRent: null,
    nightlyRate: 185,
    rating: 4.8,
    reviews: 127,
    availability: {
      '2026-09-20': true,
      '2026-09-21': true,
      '2026-09-22': true,
      '2026-09-23': true,
      '2026-09-24': true,
      '2026-09-25': true,
    },
  },
  {
    id: 'prop-4',
    slug: '310-lake-drive-houston-tx',
    address: '310 Lake Drive',
    city: 'Houston',
    state: 'TX',
    zip: '77001',
    price: 525000,
    type: 'Townhouse',
    bedrooms: 4,
    bathrooms: 3,
    size: 2200,
    lotSize: 3500,
    yearBuilt: 2018,
    status: 'For Sale',
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    ],
    description: 'Spacious townhouse near Houston lake with modern amenities. Master suite with balcony, attached garage, and low HOA fees.',
    features: ['Garage', 'Balcony', 'HOA', 'Central AC', 'Smart Home'],
    estimatedValue: { min: 515000, max: 540000 },
    monthlyRent: null,
    nightlyRate: null,
    rating: null,
    reviews: null,
    availability: null,
  },
];

export const savedProperties = [
  { id: 'saved-1', propertyId: 'prop-1', collection: 'My Favorites', savedAt: 'Sep 01, 2026' },
  { id: 'saved-2', propertyId: 'prop-4', collection: 'Austin Homes', savedAt: 'Sep 03, 2026' },
];

export const savedSearches = [
  {
    id: 'search-1',
    name: 'Austin 3 Bedroom Homes',
    intent: 'Buy',
    criteria: { location: 'Austin, TX', bedrooms: '3+', priceRange: '$350k-$500k', propertyType: 'House' },
    alertsEnabled: true,
    createdAt: 'Aug 28, 2026',
  },
  {
    id: 'search-2',
    name: 'Lisbon Weekend Stays',
    intent: 'Stay',
    criteria: { location: 'Lisbon, Portugal', guests: 2, dates: 'Weekends' },
    alertsEnabled: true,
    createdAt: 'Sep 02, 2026',
  },
];

export const buyerViewings = [
  {
    id: 'viewing-1',
    propertyId: 'prop-1',
    propertyAddress: '1824 Oak Street',
    date: 'Sep 12, 2026',
    time: '2:00 PM',
    status: 'Confirmed',
    contact: 'Sarah Johnson - Broker',
    notes: '',
  },
  {
    id: 'viewing-2',
    propertyId: 'prop-4',
    propertyAddress: '310 Lake Drive',
    date: 'Sep 15, 2026',
    time: '10:00 AM',
    status: 'Pending',
    contact: 'Michael Davis - Broker',
    notes: 'Ask about HOA fees',
  },
];

export const buyerOffers = [
  {
    id: 'offer-1',
    propertyId: 'prop-1',
    propertyAddress: '1824 Oak Street',
    offerPrice: 440000,
    financing: 'Mortgage',
    downPayment: 20,
    closingPreference: '30-45 days',
    status: 'Under Review',
    submittedAt: 'Sep 04, 2026',
    counterOffer: null,
  },
  {
    id: 'offer-2',
    propertyId: 'prop-4',
    propertyAddress: '310 Lake Drive',
    offerPrice: 510000,
    financing: 'Mortgage',
    downPayment: 15,
    closingPreference: '45-60 days',
    status: 'Countered',
    submittedAt: 'Sep 02, 2026',
    counterOffer: { price: 520000, closingPreference: '30-45 days' },
  },
];

export const buyerBookings = [
  {
    id: 'booking-1',
    propertyId: 'prop-3',
    propertyAddress: '92 Market Street',
    city: 'Lisbon',
    checkIn: 'Sep 20, 2026',
    checkOut: 'Sep 25, 2026',
    guests: 2,
    nightlyRate: 185,
    total: 925,
    cleaningFee: 80,
    platformFee: 92,
    taxes: 74,
    finalTotal: 1171,
    status: 'Confirmed',
    host: 'John Silva',
  },
];

export const buyerMessages = [
  {
    id: 'msg-1',
    propertyId: 'prop-1',
    propertyAddress: '1824 Oak Street',
    contactName: 'Sarah Johnson',
    contactRole: 'Broker',
    lastMessage: 'I can schedule that viewing for Saturday at 2pm. Does that work for you?',
    lastMessageTime: '2 hours ago',
    unread: true,
  },
  {
    id: 'msg-2',
    propertyId: 'prop-3',
    propertyAddress: '92 Market Street',
    contactName: 'John Silva',
    contactRole: 'Host',
    lastMessage: 'Check-in instructions will be sent 24 hours before your arrival.',
    lastMessageTime: '1 day ago',
    unread: false,
  },
];

export const buyerTransactions = [
  {
    id: 'trans-1',
    propertyId: 'prop-4',
    propertyAddress: '310 Lake Drive',
    purchasePrice: 510000,
    status: 'Contract',
    progress: 60,
    startDate: 'Aug 15, 2026',
    expectedClosing: 'Oct 15, 2026',
    tasks: [
      { id: 'task-1', title: 'Review purchase agreement', status: 'Completed' },
      { id: 'task-2', title: 'Schedule inspection', status: 'Completed' },
      { id: 'task-3', title: 'Secure financing', status: 'In Progress' },
      { id: 'task-4', title: 'Review closing disclosure', status: 'Pending' },
    ],
  },
];

export const buyerProfile = {
  name: 'Alex Thompson',
  email: 'alex.t@email.com',
  phone: '(512) 555-0199',
  preferredLocations: ['Austin, TX', 'Dallas, TX', 'Lisbon, Portugal'],
  preferredPropertyTypes: ['House', 'Condo'],
  budget: { buy: '$350k-$500k', rent: '$2k-$3k', stay: '$150-$250/night' },
  preferences: {
    bedrooms: '2-3',
    bathrooms: '2+',
    mustHaves: ['Parking', 'Central AC'],
  },
};
